### PR TITLE
Updating bluebird and ftp dependencies

### PR DESCRIPTION
**Pull request by gabema**
The node-ftp project appears to have become a dead project unfortunately and the most actively maintained and popular fork appears to be icetee/node-ftp.  Updating the ftp dependency includes some very useful fixes that have been withering on the vine but are sorely needed.  Also updated the bluebird version to the latest version.

Note: I haven't tested the changes other than to ensure it builds. Could use some help with that.  No tests in this project.

### CODE REVIEW

**Comment by zacronos** [comment]
Unfortunately, it is hard to do proper tests without an FTP server to interact with, which makes tests for this project somewhat more involved than most.  I don't have access to such a server right now, and in fact the project which inspired me to create this originally is dead, so I don't have any way to test it at all without some significant effort.

If someone is able to confirm that this build seems to work properly rather than just build properly, that's good enough for me for now.  Until it's at least been used in a basic way though, I'm hesitant to merge.

**Comment by gabema** [comment]
I did some testing and can confirm that additional changes are needed before bluebird can be updated. Would you be ok with changing the ftp dependency to a more actively maintained fork of ftp?  There are some useful fixes in the more maintained fork.

**Comment by zacronos** [comment]
Looks good to me, thanks for the contribution!

**Comment by gabema** [comment]
Woah this will break unless the bluebird version change is reverted.  Updating the ftp dependency has been verified to fix known issues in the ftp dependency, but changing the bluebird version will break a lot of things. This should NOT have been merged as is.

**Comment by zacronos** [comment]
It looked to me like the bluebird version change had already been reverted; see [the diff](https://github.com/realtymaps/promise-ftp/pull/22/files).  Am I wrong?  If so I'll put out a fix, but it looks like this is not a problem.

**Comment by gabema** [comment]
ok looks good. forgot I had done that and updated the pull request. thanks for pulling in the ftp updates!

**Pull request merged**
